package com.njwyt.entity.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.njwyt.entity.GuestRecording;
import com.njwyt.entity.MessageHistory;
import com.njwyt.entity.User;

import com.njwyt.entity.greendao.GuestRecordingDao;
import com.njwyt.entity.greendao.MessageHistoryDao;
import com.njwyt.entity.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig guestRecordingDaoConfig;
    private final DaoConfig messageHistoryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final GuestRecordingDao guestRecordingDao;
    private final MessageHistoryDao messageHistoryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        guestRecordingDaoConfig = daoConfigMap.get(GuestRecordingDao.class).clone();
        guestRecordingDaoConfig.initIdentityScope(type);

        messageHistoryDaoConfig = daoConfigMap.get(MessageHistoryDao.class).clone();
        messageHistoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        guestRecordingDao = new GuestRecordingDao(guestRecordingDaoConfig, this);
        messageHistoryDao = new MessageHistoryDao(messageHistoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(GuestRecording.class, guestRecordingDao);
        registerDao(MessageHistory.class, messageHistoryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        guestRecordingDaoConfig.getIdentityScope().clear();
        messageHistoryDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public GuestRecordingDao getGuestRecordingDao() {
        return guestRecordingDao;
    }

    public MessageHistoryDao getMessageHistoryDao() {
        return messageHistoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
