package com.njwyt.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.njwyt.entity.GuestRecording;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GUEST_RECORDING".
*/
public class GuestRecordingDao extends AbstractDao<GuestRecording, Long> {

    public static final String TABLENAME = "GUEST_RECORDING";

    /**
     * Properties of entity GuestRecording.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uuid = new Property(0, Long.class, "uuid", true, "_id");
        public final static Property Datatime = new Property(1, String.class, "datatime", false, "DATATIME");
        public final static Property RecordingUrl = new Property(2, String.class, "recordingUrl", false, "RECORDING_URL");
        public final static Property GuestPicUrl = new Property(3, String.class, "guestPicUrl", false, "GUEST_PIC_URL");
        public final static Property Duration = new Property(4, int.class, "duration", false, "DURATION");
        public final static Property IsRead = new Property(5, boolean.class, "isRead", false, "IS_READ");
    };


    public GuestRecordingDao(DaoConfig config) {
        super(config);
    }
    
    public GuestRecordingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GUEST_RECORDING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uuid
                "\"DATATIME\" TEXT," + // 1: datatime
                "\"RECORDING_URL\" TEXT," + // 2: recordingUrl
                "\"GUEST_PIC_URL\" TEXT," + // 3: guestPicUrl
                "\"DURATION\" INTEGER NOT NULL ," + // 4: duration
                "\"IS_READ\" INTEGER NOT NULL );"); // 5: isRead
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GUEST_RECORDING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GuestRecording entity) {
        stmt.clearBindings();
 
        Long uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindLong(1, uuid);
        }
 
        String datatime = entity.getDatatime();
        if (datatime != null) {
            stmt.bindString(2, datatime);
        }
 
        String recordingUrl = entity.getRecordingUrl();
        if (recordingUrl != null) {
            stmt.bindString(3, recordingUrl);
        }
 
        String guestPicUrl = entity.getGuestPicUrl();
        if (guestPicUrl != null) {
            stmt.bindString(4, guestPicUrl);
        }
        stmt.bindLong(5, entity.getDuration());
        stmt.bindLong(6, entity.getIsRead() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GuestRecording entity) {
        stmt.clearBindings();
 
        Long uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindLong(1, uuid);
        }
 
        String datatime = entity.getDatatime();
        if (datatime != null) {
            stmt.bindString(2, datatime);
        }
 
        String recordingUrl = entity.getRecordingUrl();
        if (recordingUrl != null) {
            stmt.bindString(3, recordingUrl);
        }
 
        String guestPicUrl = entity.getGuestPicUrl();
        if (guestPicUrl != null) {
            stmt.bindString(4, guestPicUrl);
        }
        stmt.bindLong(5, entity.getDuration());
        stmt.bindLong(6, entity.getIsRead() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GuestRecording readEntity(Cursor cursor, int offset) {
        GuestRecording entity = new GuestRecording( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uuid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // datatime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // recordingUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // guestPicUrl
            cursor.getInt(offset + 4), // duration
            cursor.getShort(offset + 5) != 0 // isRead
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GuestRecording entity, int offset) {
        entity.setUuid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDatatime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRecordingUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGuestPicUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDuration(cursor.getInt(offset + 4));
        entity.setIsRead(cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GuestRecording entity, long rowId) {
        entity.setUuid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GuestRecording entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
