package com.njwyt.entity.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.njwyt.entity.MessageHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE_HISTORY".
*/
public class MessageHistoryDao extends AbstractDao<MessageHistory, Long> {

    public static final String TABLENAME = "MESSAGE_HISTORY";

    /**
     * Properties of entity MessageHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Uuid = new Property(0, Long.class, "uuid", true, "_id");
        public final static Property SenderId = new Property(1, Long.class, "senderId", false, "SENDER_ID");
        public final static Property TargetId = new Property(2, Long.class, "targetId", false, "TARGET_ID");
        public final static Property Datatime = new Property(3, String.class, "datatime", false, "DATATIME");
        public final static Property VideoUrl = new Property(4, String.class, "videoUrl", false, "VIDEO_URL");
        public final static Property FirstFrameUrl = new Property(5, String.class, "firstFrameUrl", false, "FIRST_FRAME_URL");
        public final static Property IsRead = new Property(6, boolean.class, "isRead", false, "IS_READ");
        public final static Property Duration = new Property(7, int.class, "duration", false, "DURATION");
    };


    public MessageHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public MessageHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE_HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uuid
                "\"SENDER_ID\" INTEGER," + // 1: senderId
                "\"TARGET_ID\" INTEGER," + // 2: targetId
                "\"DATATIME\" TEXT," + // 3: datatime
                "\"VIDEO_URL\" TEXT," + // 4: videoUrl
                "\"FIRST_FRAME_URL\" TEXT," + // 5: firstFrameUrl
                "\"IS_READ\" INTEGER NOT NULL ," + // 6: isRead
                "\"DURATION\" INTEGER NOT NULL );"); // 7: duration
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MessageHistory entity) {
        stmt.clearBindings();
 
        Long uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindLong(1, uuid);
        }
 
        Long senderId = entity.getSenderId();
        if (senderId != null) {
            stmt.bindLong(2, senderId);
        }
 
        Long targetId = entity.getTargetId();
        if (targetId != null) {
            stmt.bindLong(3, targetId);
        }
 
        String datatime = entity.getDatatime();
        if (datatime != null) {
            stmt.bindString(4, datatime);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(5, videoUrl);
        }
 
        String firstFrameUrl = entity.getFirstFrameUrl();
        if (firstFrameUrl != null) {
            stmt.bindString(6, firstFrameUrl);
        }
        stmt.bindLong(7, entity.getIsRead() ? 1L: 0L);
        stmt.bindLong(8, entity.getDuration());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MessageHistory entity) {
        stmt.clearBindings();
 
        Long uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindLong(1, uuid);
        }
 
        Long senderId = entity.getSenderId();
        if (senderId != null) {
            stmt.bindLong(2, senderId);
        }
 
        Long targetId = entity.getTargetId();
        if (targetId != null) {
            stmt.bindLong(3, targetId);
        }
 
        String datatime = entity.getDatatime();
        if (datatime != null) {
            stmt.bindString(4, datatime);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(5, videoUrl);
        }
 
        String firstFrameUrl = entity.getFirstFrameUrl();
        if (firstFrameUrl != null) {
            stmt.bindString(6, firstFrameUrl);
        }
        stmt.bindLong(7, entity.getIsRead() ? 1L: 0L);
        stmt.bindLong(8, entity.getDuration());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MessageHistory readEntity(Cursor cursor, int offset) {
        MessageHistory entity = new MessageHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uuid
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // senderId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // targetId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // datatime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // videoUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // firstFrameUrl
            cursor.getShort(offset + 6) != 0, // isRead
            cursor.getInt(offset + 7) // duration
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MessageHistory entity, int offset) {
        entity.setUuid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSenderId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTargetId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setDatatime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVideoUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFirstFrameUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsRead(cursor.getShort(offset + 6) != 0);
        entity.setDuration(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MessageHistory entity, long rowId) {
        entity.setUuid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MessageHistory entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
